config-production.xml
src/pages/SigninPage.js
src/pages/SignupPage.js
src/styles/pages/SignPage.scss
src/utils/config.js

Le principe : 
Avoir les boutons de formulaire en bas d'écran autant que possible, tout en préservant un scroll correct. Ne pas avoir les boutons qui remontent lorsqu'on ouvre le clavier virtuel, ne pas perturber les fonctionnalités de scroll automatique vers l'input en cours lorsqu'on ouvre le clavier (ce qui nécessite que le scroll se fasse sur le body ou une div qui fait 100% du body et pas une sous-div d'après mes tests).
Limitation: pas de moyen fiable de detecter le clavier virtuel en web.
Donc:
- boutons (footer) en position:absolute bottom:0 dans l'appli clavier fermé avec scroll sur le conteneur au dessus des boutons
- boutons (footer) en position:static, mais min-height qui pousse les boutons en bas de l'écran dans l'appli clavier ouvert ou sur le web avec scroll sur l'écran …

Gestion correcte des boutons de formulaires avec le clavier virtuel

---

src/selectors/tests/selectBookables.spec.js
testcafe/01_signup.js
testcafe/02_signin.js
testcafe/05_search.js
testcafe/helpers/roles.js

- le retour d'erreurs d'api avait changé
- on ne cherche plus une url exacte (par exemple /recherche) mais une url qui contient /recherche (car pour le moment, on n'a pas de base de test fixe et on voit les cartes découvertes)

767 reparer circle ci testcafe

---

src/components/pages/discovery/DeckNavigation.js
src/styles/components/DeckNavigation.scss

L'erreur en elle même ne cassait pas la navigation, le clic n'était pas pris en compte sur les button (flèche) de navigation car le z-index était setté sur l'image contenue par les boutons.
Sous chrome l'event "bubble" jusqu'au button container, mais pas sous FF.

PC-1110 deck navigation broken on Firefox

---

scripts/pc.js
src/components/pages/discovery/index.js
src/components/pages/discovery/tests/__snapshots__/index.spec.js.snap
src/components/pages/discovery/tests/index.spec.js

Le composant Main avait le vilain defaut de lancer deux requetes PUT recommendations à la suite en moins de qqes ms, ce qui etait pas bien compris par le backend (car ca causait le fait de creer en doublon des cartes reco tutos).
Du coup là... en passant, pour eviter que DiscoveryPage n'appelle pas en doublon PUT recommendations, c'etait plus simple de lui faire enlever le composant Main qu'on doit enlever d'ailleurs partout quand on peut:).

453 - [POST PO REVIEW FIX] - removed Main from index of discovery page

---

scripts/pc.js

pour eviter le problème de devoir faire un chmod de node_modules/testcafe/testcafe.js quand on lance la commande pc test-cafe-webapp en dev.

choose node_modules/.bin/testcafe instead of node_modules/testcafe/testcafe.js script

---

src/components/pages/SearchPageContent.js
src/components/pages/search/FilterByDates.js
src/components/pages/search/FilterByDistance.js
src/components/pages/search/SearchFilter.js
src/components/pages/search/tests/FilterByDates.spec.js
src/components/pages/search/tests/SearchFilter.spec.js
src/components/pages/search/tests/__snapshots__/FilterByDates.spec.js.snap
src/components/pages/tests/SearchPageContent.spec.js

Solution à challenger ! 
Il fallait informer le filter by dates du fait que la date a été réinitialisée car le date picker n'avait pas accès à cette information.

Pc 1329 fix filters reinitialization

---

package.json
src/components/pages/my-bookings/connect.js
src/components/pages/my-bookings/index.js
src/selectors/selectBookings.js
src/selectors/tests/data/selectBookings.js
src/selectors/tests/selectBookings.spec.js
src/utils/routes.js
src/utils/tests/routes-utils.spec.js

- par defaut a la creation du compte user, on cree automatiquement une offre de reservation de type numerique
- il faut masquer cette offre afin que l'user n'est pas acces a la contremarque
- j'ai bougé le fichier MyBookingsPage dans le fichier my-bookings/index.js et mis le mapStateToProps dans le fichier connect
[Ticker JIRA](https://passculture.atlassian.net/browse/PC-1318)

pc-1318 masquer les offres d'activations de types thing

---

src/components/share/ShareButton.js
src/components/share/ShareButtonContent.js
src/components/share/SharePopinContent.js
src/components/share/tests/ShareButtonContent.spec.js
src/components/share/tests/__snapshots__/ShareButtonContent.spec.js.snap

Je ne peux pas tester l'impact de mes changements sur le partage natif Android, car la fonctionnalité semble avoir disparu avec les dernières mises à jour de Chrome pour Android… j'ai pingé Google. Au pire, vu que le partage natif est dans un try/catch avec le catch qui dégrade en partage "pass Culture", ça ne peut pas être un gros drame si j'ai fait une bêtise pour le partage natif.

[PC-1270] Adapt text when sharing based on Ion's recommendations

---

.circleci/config.yml

cf. https://discuss.circleci.com/t/cannot-install-php-7-1-on-machine-because-of-locked-var-lib-dpkg-lock-file/24639/21

Add sleep before apt-get in circle-ci config to avoid error on apt lock file

---

package.json

Valeurs par défaut (cf. https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--selector-timeout-ms):
--selector-timeout 10000
--assertion-timeout 3000

Increase default timeouts for testcafe in yarn test:cafe

---

src/components/pages/SignupPage.js
src/components/pages/tests/SignupPage.spec.js

@sofcalca @arnoo 
Au passage cette PR permet de montrer une façon de tester en complete mount les composants des Apps. (Ce qui peut servir à remplacer qquns de nos testcafes end to end overkill). L'idée est que si on arrive à prouver que nos tests appellent de la bonne facon les requestData... On a dans pas mal de cas prouvé le fonctionnement, car ensuite la robustesse de requestData est testée itself dans son repo et on devrait lui faire confiance comme finalement on fait confiance desormais à history.push ou dispatch qui sont des outils externes.
Les règles à suivre:
- utiliser le configureStore de l'app (et pas un mockStore)
- faire un jest.mock('redux-saga-data') pour mocker requestData
- ne pas oublier d'encapsuler le component teste dans Provider et Router, donc on pourrait limite …

(pC-50) change webapp signup route

---

src/helpers/getPriceRangeFromStocks.js
src/helpers/tests/getPriceRangeFromStocks.spec.js

Une offre pouvait retourner une array de prix [0, 0, 0, 0, 0...]
La fonction getPriceFromRangeStocks retourne désormais un array de valeurs uniques

[PC-1619] remove duplicates values from price range stocks

---

src/components/menu/MenuItem.js
src/components/menu/tests/MenuHeader.spec.js
src/components/menu/tests/MenuItem.spec.js
src/components/menu/tests/utils.spec.js
src/components/menu/utils.js

Use Case:
- ouvrir la recherche
- cliquer sur une vignette de catégorie
- ouvrir le menu principal
- cliquer sur l'item du menu "recherche"
-> L'URL doit garder le search, actuellement ce n'est pas le cas, ca casse internet
-> A tester sur d'autres pages contenant une search query

(PC-1518) fix back to current page from menu with a search query

---

src/helpers/filterAvailableStocks.js
src/helpers/tests/filterAvailableStocks.spec.js

Problème résolu : quand on mettait une date de réservation côté pro à l'heure d'aujourd'hui, on ne le voyait pas côté webapp.

(PC-1674) afficher l'événement de la date du jour sur un booking

---

src/components/pages/search/Search.js

Voir les derniers commentaires de Nicolas sur
https://passculture.atlassian.net/browse/PC-1953
Et du coup ca fixe aussi le 
'''
Impossible de décocher un filtre, si je séléctionne une distance, que je filtre puis que j’ouvre à nouveau les filtres, impossibles de décoché le filtre choisi, il se re-coche immédiatement
'''
(car le probleme c'est que le scroll cassé, ca triggerait la demande de la page n+1 toutes les 2s et donc demandait à l'history de repusher un url de page avec les parametres précédents)

(pC-1953) fix scroll removing is-relative

---

src/selectors/currentRecommendation/getCurrentRecommendationOfferName.js
src/selectors/tests/getcurrentRecommendationOfferName.spec.js

Permettant de refaire passer les tescafés, notamment pour les PRs 2049 et MOB

guard on recommendation in getCurrentRecommendationOfferName

---

src/components/forms/inputs/DatePickerField/DatePickerField.jsx
src/components/layout/Booking/Booking.jsx
src/components/layout/Booking/BookingForm/BookingFormContent/BookingFormContent.jsx
src/components/layout/Booking/BookingForm/BookingFormContent/__specs__/BookingFormContent.spec.jsx
src/components/layout/Booking/BookingForm/BookingFormContent/__specs__/__snapshots__/BookingFormContent.spec.jsx.snap
src/components/layout/Booking/utils/parseHoursByStockId.js
src/components/pages/search/FilterControls/FilterByDates.jsx
src/components/pages/search/FilterControls/__specs__/__snapshots__/FilterByDates.spec.jsx.snap
src/styles/components/layout/Booking/index.scss
src/styles/components/pages/search/searchFilters/_SearchFilter.scss
src/styles/global/_datepicker.scss
src/styles/global/_forms.scss
testcafe/04_verso.js

Le bug venait du fait qu'en chrome:headless, le calendrier est affiché en vision withPortal. Et dans ce cas precis: cliquer sur la selectedDate.nth(0) dans testcafé ne déclenche pas le close on select du calendrier (car en fait selectedDate.nth(0) est déjà la data préselectionnée).
Du coup:
- Premierement, on passe tout quand en withPortal car la vision sans est moche et depasse du cadre
- on fait en sorte qu'il n'y ait pas de date preselectionnée au montage du calendrier. Comme ça  cliquer selectedDate.nth(0) revient bien à choisir une date et declenche la fermeture du calendrier.
- il faut faire un petit hack de style sur .--keyboard-selected des dates, car quand le calendrier n'a pas de date selectionné, il affiche en style "selected" quand meme la premiere date de l'array …

(pC-2253) fix calendar date testcafe

---

src/components/pages/search/Results/Results.jsx

A cause de ce commit https://github.com/betagouv/fetch-normalize-data/commit/57462fcf2274d2e530112b0efec3ce4cca777c59.
Le `dispatch(successData(payload, config))` a été intervertie.

add componentDidMount to Results

---

package.json
src/components/layout/Teaser/__specs__/TeaserContainer.spec.js
src/components/pages/profile/RemainingCredit/__specs__/RemainingCredit.spec.jsx
src/components/pages/search-algolia/Result/__specs__/Result.spec.jsx
src/utils/date/__specs__/date.spec.js
yarn.lock

NodeJS builds prior to Node 13 is shipped with small ICU support, which means Node takes system-wide ICU configuration for some features, like toLocaleDateString that we are using (https://nodejs.org/dist/latest-v12.x/docs/api/all.html#intl_build_with_a_pre_installed_icu_system_icu). MacOS is also shipped with small ICU support, so it doesn't fully support this feature. Other linux-based systems use different ICU configurations so we never get the same date output regarding the OS where tests are executed. Web browsers, however, implements full ICU support so the running production version is not concerned, it is just for development and tests execution.

(FIX-locale-date) Fix locale date partial support prior to Node 13

---

src/components/pages/discovery-v2/DiscoveryContainer.js
src/components/pages/discovery-v2/__specs__/DiscoveryContainer.spec.js
src/components/pages/discovery-v3/DiscoveryContainer.js
src/components/pages/discovery-v3/__specs__/DiscoveryContainer.spec.js

On envoyait les recoId avant et avec la vue matérialisée, on a besoin de l'offerId.
La v3 a été mise à jour aussi.

(pC-3167) transform recoId to offerId on Discovery

---

src/components/pages/search-algolia/Filters/Filters.jsx
src/components/pages/search-algolia/Filters/__specs__/Filters.spec.jsx
src/components/pages/search-algolia/Result/SearchResults.jsx
src/components/pages/search-algolia/Result/__specs__/SearchResults.spec.jsx

Je ne suis pas parvenu à faire un revert digne de ce nom, il y avait trop de commits dans la feature, incluant trop de refacto sur lequel les commits d'autres features s'appuyaient. Donc la résolution de conflit, pour qu'elle passe supprimait aussi les fonctionnalités des commits d'après. J'ai donc mis en commentaire les parties de code afin de désactiver juste cette fonctionnalité de slider kilométrique. J'ai préfixé chaque commentaire de `//radiusRevert:` pour que ce soit plus simple de les retrouver afin de les enlever. Je n'aime pas ça du tout, mais je n'ai pas mieux.

(PC-3121) Commented code to not show radius slider

---

src/components/pages/discovery-v2/selectors/selectCurrentRecommendation.js
src/components/pages/discovery-v2/selectors/selectNextRecommendation.js
src/components/pages/discovery-v2/selectors/selectPreviousRecommendation.js
src/components/pages/discovery-v3/selectors/selectCurrentRecommendation.js
src/components/pages/discovery-v3/selectors/selectNextRecommendation.js
src/components/pages/discovery-v3/selectors/selectPreviousRecommendation.js

**Actuellement** : 
SelectCurrentRecommendation, SelectPreviousRecommendation et SelectNextRecommendation sont des sélecteurs crées avec re-reselect qui cache dans le service worker ces sélecteurs.
Il s'avère que ces sélecteurs ont changé et ne se base plus sur les mêmes données. Il n'y a plus de filtres sur les tutoriels par exemple.
Du coup, pour que le carrousel re-fonctionne actuellement, il faut vider les données enregistrées dans le service worker de l’application.
**Dans cette PR** : 
- On remplace les sélecteurs cachés par des sélecteurs normaux.

(pC-3222): transform recommendations cached selectors to normal selector 

---

src/components/layout/Recto/RectoContainer.js
src/components/layout/Recto/__specs__/RectoContainer.spec.js
src/components/pages/my-bookings/MyBookingsLists/BookingsList/BookingItem/BookingItem.jsx
src/components/pages/my-bookings/MyBookingsLists/BookingsList/BookingItem/__specs__/BookingItem.spec.jsx
src/redux/selectors/data/thumbUrlSelector.js

Modification de la manière dont on récupère le thumbUrl pour les détails d'un booking, cette propriété n'étant plus contenue dans l'objet booking mais dans l'objet offer.

(PC-4118): Get thumbUrl via offer instead of booking

---

src/components/pages/search/Home/Home.jsx
src/components/pages/search/Home/__specs__/Home.spec.jsx
src/components/pages/search/Results/Results.jsx
src/components/pages/search/Results/__specs__/Results.spec.jsx
src/components/pages/search/Search.jsx
src/components/pages/search/__specs__/Search.spec.jsx

Vu avec @apibrac 
Ticket jira: https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=16&modal=detail&selectedIssue=PC-4538
On a remarqué que certains composants ne prenaient pas en compte les mise à jour de la prop géoloc (version ini stockée dans le state) Cette observation pourrait être liée au bug du ticket associé.
L'idée est de tester si on arrive à reproduire le bug (de ce qu'on m'a dit - pas reproductible en local et aléatoire à reproduire autrement) avec un fix du genre de cette PR. Si la résolution est KO, on pourrait ré-ouvrir la PR https://github.com/pass-culture/pass-culture-browser/pull/1831 qui devrait assurer que le bug ne se reproduise pas.
Merci d'avance pour vos retours !

Pc 4538 props geoloc search

---

src/components/pages/home/Home.jsx
src/components/pages/home/__specs__/Home.spec.jsx

Le problème venait du fait que la promesse de la géoloc était transmise de la `Home` vers la `MainView` au lieu du résultat de cette promesse. 
Ce qui était transmis: (logs du navigateur)
``` javascript
Promise {<fulfilled>: {…}}
__proto__: Promise
[[PromiseState]]: "fulfilled"
[[PromiseResult]]: Object
latitude: 48.849919799999995
longitude: 2.6370411
watchId: 1
```
Ce qui est maintenant transmis: (logs du navigateur)
```javascript
{latitude: 48.849919799999995, longitude: 2.6370411, watchId: 1}
latitude: 48.849919799999995
longitude: 2.6370411
watchId: 1
```

Pc 5043 fix geoloc homepage

---

src/components/matomo/Matomo.js
src/components/matomo/__specs__/Matomo.spec.jsx

**Lien du ticket Jira** : https://passculture.atlassian.net/browse/PC-5686
**Tests de non-régressions ajoutés** : 👍🏻 
**Cause du bug** : 
- Modification qui a introduit la régression :  https://github.com/pass-culture/pass-culture-browser/pull/1841/commits/151016548a71b0c751ce39755cdeb2e1981c20c0#diff-bca93667e42cff08b290230e2c0b287353818b23caccbb8c6ab2fa7bc3f8ee1aR32
- Explication : sans dépendances, le `useEffect` est exécuté une nouvelle fois au moment du changement de page. On a ainsi deux trigger d'events : le `useEffect` + le listener de changement de route sur `history`.

(PC-5686) Correction des events Matomo qui sont déclenchés deux fois lorsqu'on change de page

---

src/components/layout/Booking/BookingContainer.js
src/components/pages/home/Home.jsx
src/components/pages/home/MainView/MainView.jsx
src/components/pages/home/MainView/Module/Module.jsx
src/components/pages/home/MainView/Module/__specs__/Module.spec.jsx
src/components/pages/home/MainView/__specs__/MainView.spec.jsx
src/components/pages/home/MainView/domain/ValueObjects/Offers.js
src/components/pages/home/MainView/domain/ValueObjects/OffersWithCover.js
src/components/pages/home/MainView/useDisplayedHomemodules.js
src/components/pages/home/MainView/useDisplayedHomemodules.spec.js
src/components/pages/home/Profile/Header/Header.jsx
src/components/pages/home/Profile/MainView/MainView.jsx
src/components/pages/home/Profile/PersonalInformations/PersonalInformations.jsx
src/components/pages/home/Profile/RemainingCredit/RemainingCredit.jsx
src/components/pages/home/__specs__/Home.spec.jsx
src/components/pages/profile/Header/Header.jsx
src/components/pages/profile/MainView/MainView.jsx
src/components/pages/profile/PersonalInformations/PersonalInformations.jsx
src/components/pages/profile/Profile.jsx
src/components/pages/profile/RemainingCredit/RemainingCredit.jsx
src/vendor/contentful/contentful.js

Lien du ticket Jira : https://passculture.atlassian.net/browse/PC-5739
Problèmes:
- `trackAllModulesSeen` était déclenché dès le chargement de la page, pas quand l'utilisateur scrollait tout en bas de la page.
- `trackAllModulesSeen` était déclenché avec tous les modules, même ceux qui n'étaient pas forcément affichés.
Résolution:
- On affiche un Loader tant qu'on a pas tous les modules + toutes les réponses à algolia.
=> ça permet d'éviter le flicker lors du chargement de la page.
- Quand on affiche la page avec les modules, on check au premier render si on doit trigger `trackAllModulesSeen`.
- sinon on check `trackAllModulesSeen` lors du scroll.
J'en ai profité pour:
- transformer `Home` et `Module` en composant fonctionnels.
Tracking:
- que ce soit pour `AllModulesSeen` ou …

(PC-5739) Tracking systématique du AllModuleSeen

---

src/components/layout/Verso/VersoControls/booking/BookingAction/BookingAction.jsx
src/components/pages/search/Home/Home.jsx
src/components/pages/search/Home/__specs__/Home.spec.jsx

J'ai l'impression qu'une utlisation d'history.push plus en accord avec la documentation de react router fonctionne.
https://reactrouter.com/web/api/history

[PC-6320] Fix booking button on offer details

---

src/mocks/state.js

`btmx.fr` was used for historical reasons. There is no good reason to
keep using it. See also pass-culture/pass-culture-api@da378a950f79d82289ee320d999041d69b08c5df.

tests: Change testing e-mail domain to `example.com`

---

src/components/layout/Booking/Booking.jsx
src/components/layout/Booking/__specs__/Booking.spec.jsx
src/components/layout/Verso/VersoControls/Favorite/Favorite.jsx
src/components/layout/Verso/VersoControls/Favorite/__specs__/Favorite.spec.jsx
src/components/layout/Verso/VersoControls/booking/BookingAction/BookingActionContainer.js
src/components/layout/Verso/VersoControls/booking/BookingAction/__specs__/BookingAction.spec.jsx
src/components/pages/home/MainView/Module/OfferTile/OfferTile.jsx
src/components/pages/home/MainView/Module/OfferTile/__specs__/OfferTile.spec.jsx
src/components/pages/search/Home/Home.jsx
src/components/pages/search/Home/__specs__/Home.spec.jsx

**Lien du ticket** : https://passculture.atlassian.net/browse/PC-6469
**Ticket à l'origine des bugs** : https://passculture.atlassian.net/browse/PC-6320
Test unitaires de non-regressions ajoutés / mis à jours : 👍🏻 
Notes sur `react-router`: 
- Ne pas confondre `search`(query params) et `state`(que j'aime à penser comme des query params secrets) de l'objet `history.location`
- Faire attention aux différentes manières d'appeler `history.push()` : 
- `history.push(entireUrl)` 
- `history.push(pathname, state)` ==> `state` !== `search`
- `history.push({ pathname, search, state, etc... })`
- Ne pas déclarer de nouvelles propriétés sur l'objet `location` (comme par exemple `location.moduleName`). Il y a `location.state` ou `location.search` pour cela, selon si on veut que les valeurs de ces …

(PC-6469) Fix de la recherche des offres ET des analytics liés aux noms de modules

---

package.json
src/components/pages/search/Results/ResultsList/Result/__specs__/Result.spec.jsx
src/utils/date/__specs__/date.spec.js
src/utils/date/date.js
yarn.lock

Nous sommes le 28 janvier, 17h:

[PC-5511] Le filtre par date inclut des offres non disponibles à la date choisie 🐛

---

config/webpack.config.prod.js

Because the file does not have an extention, the `CopyWebpackPlugin`
assumes the destination `to` is a directory.
We need to explicitely declare the `to` destination as being the
actual file name.

(PC-6129) : Fix iOS universal link file installation

---

.env.testing

This reverts commit 9f033b49043f119a7d0a9e866757681d76d84290.

Webapp use beta.gouv.fr url that is now on GCP

---

public/_headers

Not sure why it seems the file served as "application/json" did not work.

(PC-6129) : Add content type for iOS universal links file

---

src/components/pages/beta-page/BetaPage.jsx
src/styles/components/pages/beta-page/_BetaPage.scss

Ajout d'un tabindex=0 sur l'élément titre de la page Beta, avec un focus automatique sur celui-ci.
Ce n'est pas une bonne pratique de permettre à l'utilisateur de naviguer au clavier sur un élément non interactif, mais il existe des cas exceptionnels comme celui-ci où l'on peut passer "outre" la règle.
Afin que les utilisateurs voyants ne soient pas perturbé-es par cet outline bleu sur un élément texte, il a été rendu transparent (outline: none étant "interdit") pour ne pas attirer l'attention inutilement.
Le besoin est qu'il est nécessaire de signaler aux utilisateurs non voyants qu'ils sont bien arrivés sur la page alors que l'écran de chargement est présent, afin que ceux-ci ne perdent aucune information.

(PC-7660): Add tabindex and focused state on app title

---

src/redux/selectors/data/__specs__/stocksSelectors.spec.js
src/redux/selectors/data/stocksSelectors.js

Lien des tickets : 
https://passculture.atlassian.net/browse/PC-8174
https://passculture.atlassian.net/browse/PC-8186
Les dates des stocks supprimés côté pro étaient proposés à la réservation sur le détail de l'offre et le calendrier :
En utilisant le champ isBookable on a seulement les dates réservables :

(PC-8174) utiliser le champ isBookable pour sélectionner les stocks réservables

---

src/styles/components/layout/Verso/_Verso.scss

Ajout de la propriété css `white-space: pre-line;` à `.verso-info-block` pour ne pas regrouper les sauts de ligne comme les séries de blancs pour les infos d'une offre, notamment ce qui sont rempli par l'acteur via une `<textarea/>` (ex: Modalités de retrait).
Avant :
Après:

(PC-7587): Add white-space css property to broke line at newline characters in VersoContentOffer info's

---

testcafe/04_verso.js

Fix d'un test e2e flaky côté réservation d'une offre event (provoqué par l'arrivée de nouvelles offres EAC côté sandbox).
Ajout d'une condition sur l'utilisation ou non du datepicker si l'offre a une ou plusieurs dates.

(FIX): select date via datepicker only when multiple stock
