pass-culture/pass-culture-browser

.netlify
package.json

I created one https://app.netlify.com/sites/pass-culture/overview
and one https://app.netlify.com/sites/staging-pass-culture/overview

netlify integration

---

src/Root.js
src/components/SpreadsheetItem.js
src/pages/SpreadsheetPage.js

added a spreadsheet page

---

public/icons/ico-like-w.svg
public/icons/ico-share-w.svg
src/components/Booking.js
src/components/ControlBar.js
src/components/UserMediationsDeck.js
src/styles/components/Verso.scss
src/utils/content.js
src/workers/dexie/config.js

Small Booking UI for testing the Booking API

---

src/components/Card.js
src/components/Clue.js
src/components/Deck.js
src/components/UserMediationsDeck.js
src/pages/DiscoveryPage.js
src/styles/components/Clue.scss
src/styles/components/Deck.scss
src/workers/dexie/register.js

#27 Transition deck

---

src/components/Card.js
src/components/Deck.js
src/components/Recto.js
src/components/RectoDebug.js
src/components/UserMediationsDebug.js
src/components/UserMediationsDeck.js
src/pages/DiscoveryPage.js
src/styles/components/Card.scss
src/styles/components/Recto.scss
src/styles/components/RectoDebug.scss
src/styles/components/UserMediationsDebug.scss
src/styles/components/index.scss

c'etait la branche poru fabriquer un deck qui tourne en loop... Mais en fait, 
en decidant de faire un truc plus simple, j'ai dédié cette PR à nettoyer tout le code du deck.

Cleant Deck code 

---

src/components/Card.js
src/components/Deck.js
src/components/UserMediationsDebug.js
src/components/UserMediationsDeck.js
src/pages/DiscoveryPage.js

Deck loading

---

src/components/Deck.js
src/components/UserMediationsDeck.js
src/pages/DiscoveryPage.js
src/utils/config.js
src/utils/logguers.js

added logguers with debug

---

src/components/Card.js
src/components/Deck.js
src/components/OfferInfo.js
src/components/Recto.js
src/components/UserMediationsDebug.js
src/components/UserMediationsDeck.js
src/components/Verso.js
src/pages/DiscoveryPage.js
src/styles/components/Card.scss
src/styles/components/Deck.scss
src/styles/pages/DiscoveryPage.scss
src/utils/content.js

@augnustin 
avec le nouveau fichier init.py que je suis en train de faire dans lequel il y aura des events,
j'ai un peu fixé aussi dans l'utils content la facon de recuperer les données 
... je sais pas si tu avais touché un peu à ca deja:) en tout cas c'est là pour un premier fix.
Ca va avec cette PR.
Mais il reste des ptits fix à faire des deux cotes. Du coup je finis ca demain. Enfin aujourd'hui.

[WIP] fixed content with source and venue

---

src/components/FormInput.js
src/components/Sign.js
src/components/SubmitButton.js
src/hocs/withLogin.js
src/styles/components/FormInput.scss
src/styles/components/Modal.scss
src/styles/components/Sign.scss
src/styles/defaults.scss

Cela fonctionne correctement chez moi. En revanche sur l'appli ça ne fonctionne pas.
Soit c'est lié à ma PR https://github.com/betagouv/pass-culture-api/pull/6 soit c'est carrément que le serveur associé ne fonctionne pas. Mais bon, à priori côté front c'est en place.

fixes #46: explicit login errors

---

src/components/Modal.js
src/styles/components/Modal.scss
src/styles/defaults.scss

Il faut utiliser translate sinon ça rame sur le tel !

68 menu modal

---

src/pages/BookingsPage.js
src/workers/dexie/config.js
src/workers/dexie/data.js
src/workers/dexie/index.js

#94 
@arnoo @augnustin 
need https://github.com/betagouv/pass-culture-api/pull/16 to be merged cote api
NOTE: un pc init cree deja un booking en exemple

added bookings in dexie and prepared booking page

---

src/components/ControlBar.js
src/components/Deck.js
src/components/Recto.js
src/components/Verso.js
src/components/VersoWrapper.js
src/pages/BookingsPage.js
src/reducers/navigation.js
src/selectors/headerColor.js
src/styles/components/ControlBar.scss
src/styles/components/Deck.scss
src/styles/components/MenuButton.scss
src/styles/components/Modal.scss
src/styles/components/Recto.scss
src/styles/components/Verso.scss
src/styles/components/VersoWrapper.scss

Je n'ai pas fini, mais c'est mergeable. Ca pourrait éviter certains conflits par la suite.

103 responsive design

---

src/components/Booking.js
src/components/Recto.js
src/sagas/data.js
src/utils/request.js
src/workers/dexie/data.js

139 fixed dexie not sync with dynamic post or put request

---

src/components/layout/List.js
src/components/layout/SubmitButton.js
src/components/pages/SigninPage.js
src/components/pro/OfferModify.js
src/reducers/index.js
src/reducers/queries.js
src/utils/random.js

@Ledoux je te laisse regarder. 
Ca fonctionne mais je suis moyen content de ma solution car elle ajoute pas mal de complexité du côté de `<SubmitButton />` ce qui ne devrait pas être nécessaire. Après j'utilise `getDerivedStateFromProps` ce qui devrait te faire plaisir. :smile: 
Aussi, je stocke les `queries` dans le store, mais ne vide jamais le tableau, qui pourrait donc grossir au fur et à mesure de l'utilisation de l'app. Je pourrais dire qu'une fois la requête terminée, je la supprime, mais dans ce cas, il y a un risque de race condition si une autre action a lieu entre le clic et la génération de l'action redux. Ca afficherait envoi puis l'effacerait immédiatement:
```
static getDerivedStateFromProps(newProps, prevState) {
if (prevState.submitRequestId) {
const returnedQuery = …
```

fixes #167

---

src/utils/init.js
src/utils/request.js
src/workers/dexie/config.js
src/workers/dexie/data.js
src/workers/dexie/register.js

adding geoloc to dexie

---

src/components/Booking.js

ok ca semble marcher là.
MAIS IL FAUT AUSSI merger avant https://github.com/betagouv/pass-culture-api/pull/37
@arnoo @augnustin 
quelqu'un peut tester en staging... puis en prod...?
(j'aurais pas le temps ce soir).

fixed target value of calendar booking

---

jest.config.js
jest.setup.js
package.json
src/components/pages/tests/BetaPage.test.js
src/components/pages/tests/__snapshots__/BetaPage.test.js.snap
testcafe/decouverte.js
testcafe/helpers/roles.js
testcafe/home.js
testcafe/signin.js
testcafe/signup.js
yarn.lock

Mise en place de testcafe et premiers tests
`yarn testcafe`
ou 
`testcafe 'chrome:headless' testcafe`
ou 
`testcafe chrome testcafe`

Add end to end tests

---

public/icons/ico-like-f.svg
public/index.html

http://blog.lazd.net/iNoBounce/
Ca empêche le bounce !! (Merci Augustin!)
Testé sur ios en staging. 
@arnoo @augnustin on peut tester en android ?

added iNoBounce in index.html

---

package.json
src/App.js
src/components/layout/Splash.js
src/components/pages/BetaPage.js
src/reducers/splash.js
src/styles/_variables.scss
src/styles/_zindex.scss
src/styles/components/layout/Splash.scss
src/styles/index.scss
yarn.lock

Cette branche peu être mergée par dessus la branche prettyfyin
**Les modifs:**
Ajout d'un fade out sur l'ecran splash
Fadeout seulement sur la page /beta, si on le met au lancement de l'app on pourra supprimer le reducer

Splash screen transition

---

package.json
src/Root.js
src/utils/persist.js
src/utils/persistor.js
src/utils/store.js
yarn.lock

#454 mais plus facile sans avoir fait le rebase

Redux persist bis

---

.circleci/config.yml

la branche où l'on va faire marcher les tests pour la ci de webapp:)!

added circle ci working hopefully

---

.circleci/config.yml
package.json

- add unit tests
- clean circleci config file
- add deploy to netlify testing on master

Circleci deploy testing

---

package.json
src/styles/global/form.scss
src/styles/global/index.scss

Avec le package 0.0.36 de shared

Fixed shared form checkbox

---

src/utils/pagination.js

comme cette PR (betagouv/pass-culture-api#200) sur api est enfin mergée on peut.
@annemarie35 @sixertoy du coup je merge, si vous pullez le master de webapp,
il faudra donc puller aussi le master de api pour avoir tout sync! Merci!

readapted with keywords

---

src/components/pages/signin/FormFooter.js
src/components/pages/signin/tests/FormFooter.spec.js
src/components/pages/signin/tests/FormInputs.spec.js
src/components/pages/signin/tests/__snapshots__/FormFooter.spec.js.snap
src/components/pages/signin/tests/__snapshots__/FormInputs.spec.js.snap
src/components/pages/signin/tests/__snapshots__/index.spec.js.snap
src/components/pages/signin/tests/index.spec.js
src/components/pages/tests/__snapshots__/TermsPage.spec.js.snap
src/sagas/index.spec.js

Une première couverture de tests, simple avec les snapshots.
le 
J'ai créé une issue à propos de la stratégie de test https://github.com/betagouv/pass-culture-browser/issues/914
le fichier webapp/src/components/booking/index n'est pas testé à fond par exemple

Add signin page tests jest

---

.kiss/jest.js
README.md
src/selectors/selectBookables.js
src/selectors/tests/selectBookables.spec.js

Suite au bug concernant les things avec plusieurs stocks
- Ajout de tests unitaires
- Renommage/Lisibilité des functions

🥨  ajout de tests unitaires sur les méthodes de selectBookables

---

.kiss/enzyme.js
src/components/pages/TermsPage.js
src/components/pages/tests/TermsPage.spec.js
src/components/pages/tests/__snapshots__/TermsPage.spec.js.snap
src/utils/config.js
testcafe/09_legal.js

- update du template .kiss pour les tests enzyme

Suppr du numéro de commit git, ajout du snapshot Jest + TestCafe

---

.gitignore
src/selectors/recommendations.js
src/selectors/tests/recommendations.spec.js
src/utils/geolocation.js

1076 selector recommendations refactoring

---

src/components/pages/SearchPage.js
src/components/pages/SearchPageContent.js
src/components/pages/tests/SearchPageContent.spec.js
src/components/pages/tests/__snapshots__/SearchPageContent.spec.js.snap

par rapport à https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=2&modal=detail&selectedIssue=PC-433&search=PC-

Pc 443 recherche clean state data

---

src/components/pages/discovery/Card.js
src/components/pages/discovery/DeckNavigation.js
src/components/pages/discovery/index.js
src/components/pages/discovery/tests/Card.spec.js
src/components/pages/discovery/tests/DeckNavigation.spec.js
src/components/pages/discovery/tests/__snapshots__/Card.spec.js.snap
src/components/pages/discovery/tests/__snapshots__/DeckNavigation.spec.js.snap
src/components/pages/discovery/tests/__snapshots__/index.spec.js.snap
src/components/pages/discovery/tests/index.spec.js
src/components/verso/VersoWrapper.js
src/components/verso/tests/VersoWrapper.spec.js
src/components/verso/tests/__snapshots__/VersoWrapper.spec.js.snap
src/utils/tests/colors.spec.js

J'ai corrigé le fait que la recommandation = undefined ne fasse plus crasher l'affichage de la couleur du header.
Par contre, il reste toujours la questions sur le fait que recommandation soit undefined.
Comme dans les logs d'erreurs Js, OfferId est null et ça plante, cela provient peut-être de ce bout de code : 
Mais c'est une hypothèse sortie du chapeau ^^

get thumb color from recommendation using lodash get method, add tests

---

src/App.js
src/components/layout/error-catcher/ErrorCatcherView.js
src/components/layout/error-catcher/index.js
src/components/layout/error-catcher/tests/ErrorCatcherView.spec.js
src/components/layout/error-catcher/tests/__snapshots__/ErrorCatcherView.spec.js.snap
src/components/layout/error-catcher/tests/__snapshots__/index.spec.js.snap
src/components/layout/error-catcher/tests/index.spec.js
src/styles/global/layout.scss

- wrapper autour de l'app pour intercepter les erreurs
- split de la vue d'erreur dans son proprer fichier pour rendre testable
- ajout des tests unitaires

PC-1084 Gestion des erreurs via try/catch

---

src/components/pages/search/FilterByDates.js
src/components/pages/search/tests/FilterByDates.spec.js
src/components/pages/search/tests/__snapshots__/FilterByDates.spec.js.snap

https://passculture.atlassian.net/browse/PC-1194

pc-1194 fix date issues snapshots FilterByDates

---

src/components/forms/FormError.js
src/components/forms/InputLabel.js
src/components/forms/index.js
src/components/forms/inputs/DatePickerField.js
src/components/forms/inputs/EmailField.js
src/components/forms/inputs/HiddenField.js
src/components/forms/inputs/InputField.js
src/components/forms/inputs/PasswordField.js

- ajout de l'aide contextuelle pour un input (voir écran activation)
- regroupement du composant InputLabel dans un fichier
- refacto exports du FormError

pc-1191 Creation d'un composant form label + ajout aide contextuelle

---

src/components/pages/SignupPage.js

https://passculture.atlassian.net/browse/PC-1193

pc-1193 CSS manquant sur la page inscription

---

testcafe/01_signup.js
testcafe/02_signin.js
testcafe/helpers/users.js

ils avaient disparu bizarrement dans un de mes precedents commits sur ce repo desolé...

readd disappeared tstcafes

---

src/components/layout/Finishable.js
src/components/pages/discovery/DeckNavigation.js
src/styles/components/pages/discovery.scss
src/styles/components/pages/index.scss

[Ticket JIRA](https://passculture.atlassian.net/browse/PC-1273)
- Ajout d'une feuille de style "discovery.scss"

pc-1273 fix badge terminé sur caroussel

---

src/components/booking/BookingCancel.js
src/components/booking/index.js
src/components/pages/discovery/index.js
src/components/share/CopyToClipboardButton.js
src/components/share/ShareButton.js
src/components/share/ShareButtonContent.js
src/components/share/SharePopin.js
src/components/share/SharePopinContent.js
src/components/share/tests/CopyToClipboardButton.spec.js
src/components/share/tests/ShareButtonContent.spec.js
src/components/share/tests/SharePopinContent.spec.js
src/components/share/tests/__snapshots__/CopyToClipboardButton.spec.js.snap
src/components/share/tests/__snapshots__/ShareButtonContent.spec.js.snap
src/components/share/tests/__snapshots__/SharePopinContent.spec.js.snap
src/components/verso/VersoBookingButton.js
src/components/verso/tests/VersoBookingButton.spec.js
src/selectors/selectBookings.js
src/selectors/tests/selectBookings.spec.js
src/styles/components/BookingItem.scss
src/styles/components/VersoControl.scss
src/styles/components/layout/ribbon.scss
src/utils/routes.js

~~Blocked by https://passculture.atlassian.net/browse/PC-1376 / https://github.com/betagouv/pass-culture-api/pull/370 .~~

PC-708 cancel booking

---

public/manifest.json

[PC-1244] New background color on Android launch screen

---

src/App.js
src/components/layout/Footer.js
src/components/layout/NavigationFooter.js
src/components/layout/Overlay.js
src/components/layout/tests/__snapshots__/NavigationFooter.spec.js.snap
src/components/menu/MenuItem.js
src/components/menu/ReplaceLink.js
src/components/menu/index.js
src/components/menu/tests/MenuItem.spec.js
src/components/menu/tests/__snapshots__/MenuItem.spec.js.snap
src/components/pages/SearchPageContent.js
src/components/pages/discovery/Deck.js
src/components/pages/discovery/index.js
src/components/pages/discovery/tests/Deck.spec.js
src/components/pages/discovery/tests/__snapshots__/Deck.spec.js.snap
src/components/pages/discovery/tests/__snapshots__/index.spec.js.snap
src/components/pages/discovery/tests/index.spec.js
src/components/pages/my-bookings/MyBookingItem.js
src/components/pages/profile/index.js
src/components/pages/search/tests/__snapshots__/Footer.spec.js.snap
src/components/pages/tests/__snapshots__/SearchPageContent.spec.js.snap
src/components/pages/tests/__snapshots__/TermsPage.spec.js.snap
src/reducers/index.js
src/reducers/overlay.js
src/styles/components/main-menu.scss
src/utils/routes-utils.js
src/utils/tests/routes-utils.spec.js
testcafe/12_menu.js

A review commit par commit, c'est rangé, ce sera plus simple

PC-1275 back should close menu

---

testcafe/02_signin.js
testcafe/03_decouverte.js
testcafe/05_01_search_navigate_by_types.js
testcafe/05_02_search_by_keywords.js
testcafe/05_03_search_by_filters_dates.js
testcafe/06_profil.js
testcafe/11_activation.js
testcafe/12_menu.js
testcafe/helpers/users.js

car on besoin de users avec un resetPasswordToken
https://github.com/betagouv/pass-culture-api/pull/388

(Pc 1436) added test activation

---

src/components/layout/Footer.js
src/components/layout/NavigationFooter.js

[Ticket JIRA](https://passculture.atlassian.net/browse/PC-1462)
En cause un <button> intégrant un <Link> de react-router qui génére déjà un <a>
Suppr le <button> dans layout/Footer layout/NavigationFooter
Voir
- Page Mention Légales (layout/NavigationFooter)
- Carrousel (layout/Footer)

PC-1462 suppr du tag button dans NavigationFooter et Footer

---

src/components/booking/BookingForm.js
src/components/booking/index.js
src/components/booking/tests/BookingForm.spec.js
src/components/booking/tests/__snapshots__/BookingForm.spec.js.snap
src/styles/components/Booking.scss

- suppr des styles CSS quand le form de réservation contient une seule date et une seule heure
- fix du label de la select des heures, quand le lable était pas présent

pc-1435 booking form read only

---

src/components/pages/activation/password/index.js

Ajout de la classe `pc-scroll-container` à la page activation

(PC-1476) fix du scroll sur la page activation

---

.circleci/config.yml
README.md
testcafe/01_activation.js
testcafe/01_signup.js
testcafe/02_signin.js
testcafe/03_decouverte.js
testcafe/05_01_search_navigate_by_types.js
testcafe/05_02_search_by_keywords.js
testcafe/10_menu.js
testcafe/helpers/getPageUrl.js
testcafe/helpers/users.js

- passage de la config CI avec sandbox industrial
- use jeune hasSignedUpUser97 pour l'activation
- use jeune hasSignedUpUser93 pour la connexion
- ajout d'un fichier helper pour récupérer l'URL
- update du README.md

PC-1498 utiliser sandbox industrial pour les tests CI

---

src/components/layout/Footer.js
src/components/menu/MenuHeader.js
src/components/menu/tests/MenuHeader.spec.js
src/components/menu/tests/__snapshots__/MenuHeader.spec.js.snap
src/components/pages/discovery/DeckNavigation.js
src/components/pages/discovery/index.js
src/components/pages/discovery/tests/__snapshots__/index.spec.js.snap
src/components/pages/profile/MonPassCulture.js
src/components/verso/VersoControl.js
src/utils/user/getWalletValue.js
src/utils/user/index.js
src/utils/user/isUserActivated.js
src/utils/user/tests/getWalletValue.spec.js
testcafe/04_verso.js
testcafe/helpers/getVersoWallet.js

[Ticket JIRA](https://passculture.atlassian.net/browse/PC-1557)

PC-1556 fix verso wallet value

---

src/components/Recto.js
src/components/booking/index.js
src/components/forms/utils/externalSubmitForm.js
src/components/pages/search/RawSearch.js
src/components/pages/search/RawSearchResultItem.js
src/components/pages/search/SearchDetails.js
src/components/pages/search/SearchResultItem.js
src/components/pages/search/tests/RawSearch.spec.js
src/components/pages/search/tests/RawSearchResultItem.spec.js
src/components/pages/search/tests/__snapshots__/RawSearch.spec.js.snap
src/components/pages/search/tests/__snapshots__/RawSearchResultItem.spec.js.snap
src/components/verso/VersoBookingButton.js
src/components/verso/VersoControl.js
src/components/verso/index.js
src/styles/components/Booking.scss
src/styles/components/Recto.scss
src/styles/components/Verso.scss
src/styles/components/pages/search/SearchResultItem.scss
src/styles/components/pages/search/index.scss
src/utils/routes.js
testcafe/05_01_search_navigate_by_types.js

(PC-1271) added animation to enter recherche item page and header on mediation

---

jest.setup.js
package.json
src/components/booking/tests/__snapshots__/BookingSuccess.spec.js.snap
src/components/forms/tests/__snapshots__/FormFooter.spec.js.snap
src/components/hocs/index.js
src/components/hocs/with-login/index.js
src/components/hocs/with-login/tests/OnMountCaller.js
src/components/hocs/with-login/tests/__snapshots__/withRedirectToDiscoveryWhenAlreadyAuthenticated.spec.js.snap
src/components/hocs/with-login/tests/__snapshots__/withRedirectToSigninWhenNotAuthenticated.spec.js.snap
src/components/hocs/with-login/tests/configure.js
src/components/hocs/with-login/tests/withRedirectToDiscoveryWhenAlreadyAuthenticated.spec.js
src/components/hocs/with-login/tests/withRedirectToSigninWhenNotAuthenticated.spec.js
src/components/hocs/with-login/withRedirectToDiscoveryWhenAlreadyAuthenticated.js
src/components/hocs/with-login/withRedirectToSigninWhenNotAuthenticated.js
src/components/pages/BetaPage.js
src/components/pages/FavoritesPage.js
src/components/pages/NotificationsPage.js
src/components/pages/SignupPage.js
src/components/pages/discovery/index.js
src/components/pages/my-bookings/index.js
src/components/pages/profile/index.js
src/components/pages/search/index.js
src/components/pages/signin/SigninContent.js
src/components/pages/signin/index.js
src/components/pages/signin/tests/__snapshots__/FormInputs.spec.js.snap
yarn.lock

avec la lib sur beta: https://github.com/betagouv/with-login

(PC-1629) With with-login lib

---

src/components/verso/VersoBookingButton.js

pc-1271 fixed display of description when come back from recto booking

---

README.md
config-production.xml
config-staging.xml
public/MentionsLegalesPass.md
src/components/layout/tests/MailToLink.spec.js
src/components/pages/activation/error/ActivationError.js
src/components/pages/activation/error/tests/ActivationError.spec.js
src/components/pages/activation/error/tests/__snapshots__/ActivationError.spec.js.snap
src/utils/config.js
src/utils/routes.js
src/utils/tests/routes-utils.spec.js
testcafe/01_activation.js

- add subject to support email
- update tests

[PC-1517] replace support email by support@passculture.app

---

src/components/verso/verso-content/verso-content-offer/VersoContentOffer.js
src/components/verso/verso-content/verso-content-offer/tests/VersoContentOffer.spec.js
src/components/verso/verso-content/verso-content-offer/tests/__snapshots__/VersoContentOffer.spec.js.snap
src/components/verso/verso-content/verso-content-offer/tests/utils.spec.js
src/components/verso/verso-content/verso-content-offer/utils.js
src/selectors/selectBookables.js
src/selectors/tests/selectBookables.spec.js
testcafe/03_01_decouverte.js
testcafe/04_05_verso_content.js
testcafe/05_02_search_by_keywords.js
testcafe/08_04_booking_digital_offer.js

dépend de côté api :
#https://github.com/betagouv/pass-culture-api/pull/547

(PC-1697) use specific label for webapp to describe cultural type

---

src/components/verso/verso-content/verso-content-offer/VersoContentOffer.js
src/selectors/selectBookables.js
src/selectors/tests/selectBookables.spec.js

…nd diplay réservé only for non cancelled offers

(PC-1905) Cancelled booking should not display '(réservé)' on the verso

---

src/components/forms/inputs/tests/CheckBoxField.spec.js
src/components/forms/inputs/tests/__snapshots__/CheckBoxField.spec.js.snap
src/components/layout/tests/Finishable.spec.js
src/components/layout/tests/__snapshots__/Finishable.spec.js.snap
src/components/pages/discovery/tests/__snapshots__/index.spec.js.snap
src/components/pages/discovery/tests/index.spec.js
src/components/pages/signin/tests/Signin.spec.js
src/components/pages/signin/tests/__snapshots__/Signin.spec.js.snap

Correction d'erreurs JS que l'on voyait par exemple ici : https://circleci.com/gh/betagouv/pass-culture-browser/2538 dans la partie "Running Unit Tests".

(PC-1772) fix JS errors within tests

---

src/components/pages/typeform/TypeForm.js
src/components/pages/typeform/TypeFormContainer.js
src/components/pages/typeform/tests/TypeForm.spec.js
src/components/pages/typeform/tests/TypeFormContainer.spec.js
src/components/pages/typeform/tests/__snapshots__/TypeForm.spec.js.snap

@sixertoy ... je voudrais qu'on essaye ça aussi... on est sur un combat de PR zut pardon :p.

(pC-2004) uniqId au temps du constructor

---

.circleci/config.yml

This reverts commit 4908facdb62a2282e481f05b53e840256dcbface.

Revert "(pC-2139) remove coveralls on CI config"

---

src/styles/components/pages/my-favorites/_MyFavorites.scss
src/styles/global/_ellipsis.scss

Les commentaires sont obligatoires à cause de https://github.com/postcss/autoprefixer/issues/1141.
Je n'ai pas trouvé meilleure solution.

(pC-1996) fix padding and -webkit-box-orient on my favorites list

---

src/components/matomo/Matomo.js
src/components/matomo/MatomoContainer.js
src/components/matomo/__specs__/Matomo.spec.jsx
src/components/matomo/__specs__/MatomoContainer.spec.js

@Akhilian je ne sais pas ce qui s'est passé :( mon commit a disparu suite à un amend

PC-2137 add userId matomo tracking

---

src/components/layout/Verso/verso-content/VersoContentOffer/VersoContentOffer.jsx
src/components/layout/Verso/verso-content/VersoContentOffer/VersoContentOfferContainer.js
src/components/layout/Verso/verso-content/VersoContentOffer/__specs__/VersoContentOffer.spec.jsx
src/components/layout/Verso/verso-content/VersoContentOffer/__specs__/__snapshots__/VersoContentOffer.spec.jsx.snap
src/styles/components/layout/Verso/_verso-wrapper.scss
testcafe/06_booking_list.js

Plus un peu de simplification HTML avec.

(pC-1847) no offer link when cancelled my offer

---

src/components/layout/Share/ShareButton/__specs__/ShareButtonContainer.spec.jsx
src/components/layout/Share/SharePopin.jsx
src/components/layout/Share/__specs__/SharePopin.spec.jsx
src/components/layout/Verso/VersoControls/booking/CancelThisLink/CancelThisLinkContainer.js
src/components/layout/Verso/VersoControls/booking/CancelThisLink/__specs__/CancelThisLinkContainer.spec.jsx
src/reducers/__specs__/share.spec.js
src/reducers/share.js

car on clique dessus, ca devrait redirect en enlevant le pathname params /annulation, mais ca ne le fait pas.
Comme ce bouton est redondant avec le "Non" à cliquer qui fait la meme chose, on peut l'enlever ?

removed cancel thus link close button redirecting badly

---

src/components/forms/FormFooter.jsx
src/components/forms/__specs__/FormFooter.spec.jsx
src/components/forms/__specs__/__snapshots__/FormFooter.spec.jsx.snap
src/components/layout/Booking/BookingSuccess/__specs__/BookingSuccess.spec.jsx
src/components/layout/Booking/BookingSuccess/__specs__/__snapshots__/BookingSuccess.spec.jsx.snap
src/components/layout/Booking/__specs__/Booking.spec.jsx
src/components/layout/Booking/__specs__/__snapshots__/Booking.spec.jsx.snap
src/components/layout/Overlay/__specs__/Overlay.spec.jsx
src/components/layout/Overlay/__specs__/__snapshots__/Overlay.spec.jsx.snap
src/components/layout/Share/ShareButton/__specs__/ShareButton.spec.jsx
src/components/layout/Teaser/Teaser.jsx
src/components/layout/Teaser/TeaserContainer.js
src/components/layout/Teaser/__specs__/Teaser.spec.jsx
src/components/layout/Teaser/__specs__/TeaserContainer.spec.js
src/components/layout/Teaser/__specs__/__snapshots__/Teaser.spec.jsx.snap
src/components/layout/Teaser/utils/__specs__/statuses.spec.js
src/components/layout/Teaser/utils/statuses.js
src/components/pages/activation/PasswordForm/PasswordForm.jsx
src/components/pages/activation/PasswordForm/__specs__/PasswordForm.spec.jsx
src/components/pages/forgot-password/SuccessView.jsx
src/components/pages/my-bookings/MyBookingsLists/BookingsList/BookingItem/BookingItemContainer.js
src/components/pages/search/FilterControls/__specs__/FilterByDates.spec.jsx
src/components/pages/search/FilterControls/__specs__/__snapshots__/FilterByDates.spec.jsx.snap
src/components/pages/signin/Signin.jsx

J'ai corrigé des warning sur les test en mode BSR dans un second commit.

(pC-2337) select beggining date time via stock on my favorites

---

src/components/pages/search-algolia/SearchAlgolia.jsx
src/styles/_reset.scss
src/styles/components/pages/search-algolia/_SearchAlgolia.scss
src/styles/index.scss

(PC-2951) : Fixed scroll on last element, fixed hidden search button,

---

src/components/pages/search-algolia/Result/SearchResults.jsx
src/components/pages/search-algolia/Result/__specs__/SearchResults.spec.jsx
src/components/pages/search-algolia/__specs__/SearchAlgolia.spec.jsx

Also fixed some props validation warnings

(PC-3005): removed pagination in result page to fix go back behavior

---

config/webpack.config.dev.js

https://github.com/facebook/create-react-app/pull/7587
https://webpack.js.org/loaders/eslint-loader/#cache

(pC-3260) reduce time from eslint loader

---

src/styles/components/pages/beta-page/_BetaPage.scss
src/styles/components/pages/discovery/Deck/Navigation/_Navigation.scss
src/styles/components/pages/my-bookings/MyBookingsList/BookingsList/QrCode/_QrCode.scss
src/styles/components/pages/profile/_RemainingCredit.scss
src/styles/components/pages/search-algolia/Home/_Home.scss
src/styles/components/pages/search-algolia/Result/_SearchResults.scss
src/styles/components/pages/signin/_Signin.scss
src/styles/global/_forms.scss
src/styles/global/_frame.scss
src/styles/global/_themes.scss
src/styles/variables/_colors.scss

J'en ai profité pour mettre en variable (comme une couleur) tout ce qui concernait les différents `linear-gradient`.

(pC-3376) refacto gradient background image

---

src/styles/components/layout/Booking/_Booking.scss
src/styles/components/layout/Modal/_Modal.scss
src/styles/components/layout/NavBar/_NavBar.scss
src/styles/components/layout/Ribbon/_Ribbon.scss
src/styles/components/layout/Splash/_Splash.scss
src/styles/components/pages/discovery/Deck/Card/_Card.scss
src/styles/components/pages/profile/_Profile.scss
src/styles/components/pages/search/CriteriaLocation/Place/_Place.scss
src/styles/components/pages/search/Filters/FilterToggle/_FilterToggle.scss
src/styles/components/pages/search/Filters/_Filters.scss
src/styles/components/pages/search/Filters/_Slider.scss
src/styles/components/pages/search/Header/_Header.scss
src/styles/components/pages/search/Home/_Home.scss
src/styles/components/pages/search/Result/_Result.scss
src/styles/components/pages/search/Result/_SearchResults.scss
src/styles/global/_borders.scss
src/styles/global/_dotted.scss
src/styles/global/_forms.scss
src/styles/global/_frame.scss
src/styles/variables/_colors.scss
src/styles/variables/_guidelines.scss

- white/black => $white/$black ;
- rgba => $black-shadow et $black-background ;
- `transparent` quand c'était possible.

(PC-3849) refacto scss colors

---

src/components/pages/tutorials/Tutorials.jsx
src/components/pages/tutorials/TutorialsContainer.js
src/components/pages/tutorials/__specs__/Tutorials.spec.jsx

Utilisation d'une callback pour s'assurer que l'enregistrement s'est bien fait.

(FIX): Redirection vers découverte uniquement après avoir enregistrer le visionnage des tutos

---

src/components/pages/home/Home.jsx
src/components/pages/home/Module/Module.jsx
src/components/pages/home/Module/OfferTile/OfferTile.jsx
src/components/pages/home/OfferDetails/OfferDetailsContainer.js
src/components/pages/home/__specs__/Home.spec.jsx
src/components/pages/home/repository/getOffer.js
src/components/pages/profile/Profile.jsx
src/components/pages/profile/repository/updateUser.js
src/components/router/routes.jsx
src/styles/components/pages/home/Module/_Module.scss
src/styles/components/pages/home/_Home.scss

Bonus :
- amélioration de sémantique ;
- micro refacto sur d'autres fichiers.

pC-3939 handle offer details from home

---

src/components/pages/my-bookings/MyBookingsLists/BookingsList/BookingItem/BookingItem.jsx
src/components/pages/my-bookings/MyBookingsLists/BookingsList/BookingItem/__specs__/BookingItem.spec.jsx
src/components/pages/my-bookings/MyBookingsLists/BookingsList/BookingItem/__specs__/__snapshots__/BookingItem.spec.jsx.snap

Reverts betagouv/pass-culture-browser#1694

Revert "(PC-3976): Get thumbUrl from offer"

---

src/components/pages/home/domain/__specs__/parseAlgoliaParameters.spec.js
src/components/pages/home/domain/parseAlgoliaParameters.js

Reverts betagouv/pass-culture-browser#1724

Revert "(PC-4027): Added ability to fetch offer with price range"

---

public/index.html

PR pour ajouter les SDK facebook et Google
| sdk facebook | sdk google | 
|---------------|-----------|
|![fbsdk](https://user-images.githubusercontent.com/66383742/97890198-8b231c80-1d2d-11eb-903c-7541002318bb.gif)|![image](https://user-images.githubusercontent.com/66383742/97890239-99713880-1d2d-11eb-8c87-495e7a598537.png)|

Pc 4714 facebook & google SDKs

---

src/components/layout/Finishable/Finishable.jsx
src/components/layout/Finishable/FinishableContainer.js
src/components/layout/Verso/Verso.jsx
src/components/layout/Verso/__specs__/Verso.spec.jsx

PC-3778 : fix offer details display while loading

---

yarn.lock

(PC-5317) Fix webapp dependencies security breaches

---

src/redux/selectors/data/__specs__/bookingsSelectors.spec.js
src/redux/selectors/data/bookingsSelectors.js

Update bookingsSelector to include validated bookings to upcoming bookings list

(PC-3060): Beneficiary should see their validated bookings for event

---

src/utils/timezone.js

See also pass-culture/pass-culture-api@d58134c08db2b57241ff50fe13791d3090ceafd1

(PC-5520) timezones: Handle more overseas départements

---

package.json
yarn.lock

(PC-5636) Fix offer details scroll

---

jest.setup.js
src/components/pages/create-account/EligibilityCheck.jsx
src/components/pages/create-account/__specs__/EligibilityCheck.spec.jsx
src/components/pages/home/Home.jsx
src/components/pages/home/__specs__/Home.spec.jsx
src/components/pages/signin/SignIn.jsx
src/components/pages/signin/__specs__/SignIn.spec.jsx
src/tracking/__mocks__/mediaCampaignsTracking.js
src/tracking/mediaCampaignsTracking.js

Ticket Jira : https://passculture.atlassian.net/browse/PC-5500
Tests unitaires ajoutés : :+1: 
Bonus : les tests de `Home` n'ont plus de warnings liés à `act`.

(PC-5500) Ajout des trackers (analytics) pour les campagnes média de Floodlight

---

src/tracking/mediaCampaignsTracking.js
src/tracking/mediaCampaignsTracking.spec.js

Ticket Jira : https://passculture.atlassian.net/browse/PC-5500
Tests unitaires ajoutés : :+1:

(PC-5500) Floodlight tracking : empêcher les doublons d'iframe

---

src/components/layout/Booking/Booking.jsx
src/components/layout/Booking/BookingContainer.js
src/components/layout/Booking/__specs__/BookingContainer.spec.js
src/components/layout/Verso/VersoControls/booking/BookingAction/BookingAction.jsx
src/components/layout/Verso/VersoControls/booking/BookingAction/BookingActionContainer.js

A merger avant le freeze merge, j'écris les tests unitaires de non régression dans une PR à part :)

[PC-5883] Add tracking book offer from homepage

---

src/components/pages/signin/SignIn.jsx
src/styles/components/pages/signin/_Signin.scss

Ticket : https://passculture.atlassian.net/browse/PC-3347
Dépend de cette PR dans l'api : https://github.com/pass-culture/pass-culture-api/pull/1867
Screenshots:

(PC-3347) Webapp - [Sécurité] Adapter les messages d'erreur de connexion

---

src/components/pages/create-account/IdCheckDisabled/IdCheckDisabled.jsx
src/styles/components/pages/create-account/IdCheckDisabled/_IdCheckDisabled.scss
src/styles/components/pages/create-account/IdCheckDisabled/index.scss
src/styles/components/pages/create-account/index.scss

(6244) Add email utilization warning message

---

src/styles/components/pages/create-account/IdCheckDisabled/_IdCheckDisabled.scss

(PC-6339) Fix padding in legal notice page

---

src/components/pages/search/Filters/Filters.jsx
src/components/pages/search/Filters/__specs__/Filters.spec.jsx
src/components/pages/search/Filters/filtersEnums.js
src/components/pages/search/Results/__specs__/Results.spec.jsx

https://passculture.atlassian.net/browse/PC-6438

[PC-6438] Filtre par prix - Passage du slider a 300€

---

src/components/pages/search/Results/ResultsList/Result/Result.jsx
src/components/pages/search/Results/ResultsList/Result/__specs__/Result.spec.jsx

| Hit algolia | Avant (Recherche) | Détail de l'offre | Après (Recherche) |
| --- | --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/10118284/106452965-e4176380-6488-11eb-8002-4f4916415a5b.png) | ![image](https://user-images.githubusercontent.com/10118284/106452998-ef6a8f00-6488-11eb-89b9-c5c060bd9da7.png) | ![image](https://user-images.githubusercontent.com/10118284/106453084-0f01b780-6489-11eb-9acb-db54f7107487.png) |  ![image](https://user-images.githubusercontent.com/10118284/106453108-188b1f80-6489-11eb-8b16-00bd19cceaa1.png) |

(PC-5511) Use departmentCode from venue to fix offer date on search page

---

.eslintrc
src/components/forms/inputs/HiddenField.jsx
src/components/pages/create-account/Eligible/Eligible.jsx
src/components/pages/forgot-password/RequestEmailForm/RequestEmailForm.jsx
src/components/pages/forgot-password/RequestEmailForm/__specs__/RequestEmailForm.spec.jsx
src/components/pages/forgot-password/ResetPasswordForm/ResetPasswordForm.jsx
src/components/pages/forgot-password/ResetPasswordForm/__specs__/ResetPasswordForm.spec.jsx
src/components/pages/forgot-password/hocs/withResetForm.jsx

Lien vers le ticket : https://passculture.atlassian.net/browse/PC-5665

(PC-5665) Ajouts de messages d'erreur sur les formulaire de réinitialisation de mot de passe

---

src/components/layout/Verso/VersoControls/Favorite/Favorite.jsx
src/components/layout/Verso/VersoControls/Favorite/FavoriteContainer.js
src/components/layout/Verso/VersoControls/Favorite/__specs__/Favorite.spec.jsx

https://passculture.atlassian.net/browse/PC-4301

[PC-4301] Rajouter du tracking sur la mise en favori d'une offre

---

src/components/pages/search/Results/EmptyResult/EmptyResult.jsx
src/components/pages/search/Results/EmptyResult/__specs__/EmptyResult.spec.jsx

https://passculture.atlassian.net/browse/PC-3717

(PC-3717) Change message for no result - empty query

---

src/components/pages/home/MainView/useDisplayedHomeModules.utils.js
src/components/pages/home/MainView/useDisplayedHomemodules.js
src/components/pages/home/MainView/useDisplayedHomemodules.spec.js
src/components/pages/home/MainView/useHomeAlgoliaModules.js
src/components/pages/home/MainView/useHomepageModules.js
src/components/pages/home/__specs__/Home.spec.jsx

Nothing much on this PR, just clarify some code by splitting it.

[PC-6277] Affichage du module de recommandation côté Webapp [Step 1]

---

src/components/pages/profile/ValueObjects/User.js
src/components/pages/typeform/Typeform.jsx
src/components/pages/typeform/TypeformContainer.js
src/components/pages/typeform/__specs__/Typeform.spec.jsx

Lien ticket Jira : https://passculture.atlassian.net/browse/PC-4847
Test unitaires mis à jours : 👍🏻

(PC-4847) Pass (unhumanized) user id as a query param for typeform in addition of dynamic UUID

---

src/components/pages/home/HomeContainer.js

...avec le bon nom de branche...
Commit qui a introduit la régression: 77a0f6aafb2727c97feff8e70ddb334bc02df02f (suppression de la page discovery)

 [PC-7358] Data - Objectif Matomo 'Jeunes - Est géolocalisé cassé

---

src/components/pages/profile/RemainingCredit/RemainingCredit.jsx

(PC-7001) Fix admin credit gauges display

---

src/components/pages/profile/RemainingCredit/RemainingCredit.jsx

https://passculture.atlassian.net/browse/PC-7807

(PC-7807) add text in readMoreContent profile page

---

src/components/forms/inputs/EmailField.jsx
src/components/forms/validators/__specs__/validateEmailField.spec.js
src/components/forms/validators/strings.js
src/components/forms/validators/validateEmailField.js
src/components/hocs/with-login/withLogin.jsx
src/components/pages/signin/SignIn.jsx
src/components/pages/signin/__specs__/SignIn.spec.jsx

https://passculture.atlassian.net/browse/PC-8006

(PC-8006)(Tech): Webapp - Validation du formulaire de connexion email et mot de passe

---

package.json
public/index.html
src/components/pages/beta-page/BetaPage.jsx
src/styles/components/pages/beta-page/_BetaPage.scss
yarn.lock

https://passculture.atlassian.net/browse/PC-8543
| IOS | Android |
| ------------ | ------------- |
| ![image](https://user-images.githubusercontent.com/50346870/121162521-4674dc00-c84e-11eb-8fff-d01a57ddba73.png) | ![image](https://user-images.githubusercontent.com/50346870/121162476-3bba4700-c84e-11eb-870a-031737c8b33f.png) |

(PC-8543) spike smart banner

---

src/components/pages/beta-page/BetaPage.jsx
src/components/pages/beta-page/__specs__/BetaPage.spec.jsx
src/styles/components/pages/beta-page/_BetaPage.scss

https://passculture.atlassian.net/browse/PC-8970

(PC-8970) new beta page

---

src/components/pages/home/MainView/Module/OfferTile/OfferTile.jsx
src/components/pages/home/MainView/Module/OfferTile/__specs__/OfferTile.spec.jsx
src/components/pages/home/MainView/Module/OneItem/OneItem.jsx
src/components/pages/home/MainView/Module/RecommendationModule.jsx
src/components/pages/home/MainView/Module/TwoItems/TwoItems.jsx
src/components/pages/home/MainView/useDisplayedHomemodules.js
src/components/pages/home/MainView/useHomeSearchModules.js
src/components/pages/home/__specs__/Home.spec.jsx
src/components/pages/search/Filters/Filters.jsx
src/components/pages/search/Filters/__specs__/Filters.spec.jsx
src/components/pages/search/Results/Results.jsx
src/components/pages/search/Results/ResultsList/Result/Result.jsx
src/components/pages/search/Results/ResultsList/ResultsList.jsx
src/components/pages/search/Results/__specs__/Results.spec.jsx
src/utils/getPriceRangeFromStocks.js
src/vendor/search/__specs__/buildQueryOptions.spec.js
src/vendor/search/buildAlgoliaHit.js
src/vendor/search/buildQueryOptions.js
src/vendor/search/client.js
src/vendor/search/constants.js
src/vendor/search/filters/__specs__/buildFacetFilters.spec.js
src/vendor/search/filters/__specs__/buildGeolocationFilter.spec.js
src/vendor/search/filters/__specs__/buildNumericFilters.spec.js
src/vendor/search/filters/buildFacetFilters.js
src/vendor/search/filters/buildGeolocationFilter.js
src/vendor/search/filters/buildNumericFilters.js
src/vendor/search/search.js

Ticket Jira: https://passculture.atlassian.net/browse/PC-9915
see [Utilisation des champs algolia](https://www.notion.so/passcultureapp/96f3d00762bc45aaa70f5b3ca74f117f?v=3b4309bb4cd74898a782fa83fe7701aa)

[PC-9915] Recherche - Webapp - Migrer la page d'accueil vers App Search

---

package.json
src/components/pages/home/__specs__/Home.spec.jsx
src/components/pages/home/__specs__/HomeContainer.spec.js
src/components/pages/search/Filters/Filters.jsx
src/components/pages/search/Filters/__specs__/Filters.spec.jsx
src/components/pages/search/Results/Results.jsx
src/components/pages/search/Results/ResultsList/Result/Result.jsx
src/components/pages/search/Results/ResultsList/ResultsList.jsx
src/components/pages/search/Results/__specs__/Results.spec.jsx
src/components/pages/search/Search.jsx
src/components/pages/search/SearchContainer.js
src/components/pages/search/__specs__/Search.spec.jsx
src/components/pages/search/__specs__/SearchContainer.spec.js
src/utils/dehumanizeId/__specs__/dehumanizeIds.spec.js
src/utils/dehumanizeId/dehumanizeId.js
src/vendor/search/__specs__/buildQueryOptions.spec.js
src/vendor/search/buildAlgoliaHit.js
src/vendor/search/buildQueryOptions.js
src/vendor/search/search.js
yarn.lock

Lien vers ticket JIRA: https://passculture.atlassian.net/browse/PC-9517
Réf: [Utilisation des champs algolia](https://www.notion.so/passcultureapp/96f3d00762bc45aaa70f5b3ca74f117f?v=3b4309bb4cd74898a782fa83fe7701aa)

(PC-9517) Migrer la fonctionnalité de recherche vers App Search

---

src/components/pages/search/utils/date/time.js
src/vendor/search/__specs__/buildQueryOptions.spec.js
src/vendor/search/buildQueryOptions.js
src/vendor/search/filters/__specs__/buildFacetFilters.spec.js
src/vendor/search/filters/__specs__/buildGeolocationFilter.spec.js
src/vendor/search/filters/buildFacetFilters.js
src/vendor/search/filters/buildGeolocationFilter.js
src/vendor/search/filters/buildNumericFilters.js
src/vendor/search/search.js

Lien vers le ticket JIRA: https://passculture.atlassian.net/browse/PC-9517

[PC-9517] Migrer la fonctionnalité de recherche vers App Search [part 2]

---

src/vendor/search/buildQueryOptions.js
src/vendor/search/filters/__specs__/buildBoosts.spec.js
src/vendor/search/filters/buildBoosts.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9990

(PC-9990) Add proximity boost to search

---

src/app/Root.jsx
src/app/SmartBanner.jsx
src/components/pages/beta-page/BetaPage.jsx
src/vendor/search/client.js

Lien vers le ticket  https://passculture.atlassian.net/browse/PC-9985
| iOS | Android |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10118284/127523658-a3f56642-2e02-41c0-8a46-2da5384d6ae0.png) | ![image](https://user-images.githubusercontent.com/10118284/127523839-dd42d841-52f8-4b5f-b59e-ff98d9d83b99.png) |

(PC-9985) Show smartbanner for all users

---

src/components/pages/search/utils/date/__specs__/date.spec.js
src/components/pages/search/utils/date/__specs__/time.spec.js
src/components/pages/search/utils/date/date.js
src/components/pages/search/utils/date/time.js
src/vendor/search/__specs__/buildQueryOptions.spec.js
src/vendor/search/buildAlgoliaHit.js
src/vendor/search/buildQueryOptions.js
src/vendor/search/constants.js
src/vendor/search/filters/__specs__/buildNumericFilters.spec.js
src/vendor/search/filters/__specs__/timeFilters.spec.js
src/vendor/search/filters/buildNumericFilters.js
src/vendor/search/filters/timeFilters.js
src/vendor/search/search.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10156

(PC-10156) Transform fetch functions to async functions

---

src/utils/dehumanizeId/__specs__/dehumanizeIds.spec.js
src/utils/dehumanizeId/dehumanizeId.js

https://passculture.atlassian.net/browse/PC-10375

(PC-10375) fix bug on offer id

---

src/vendor/contentful/__specs__/contentful.spec.js
src/vendor/contentful/__specs__/selectPlaylist.spec.js
src/vendor/contentful/contentful.js
src/vendor/contentful/selectPlaylist.js

Pour référence: https://github.com/pass-culture/pass-culture-app-native/pull/1675
Ticket: https://passculture.atlassian.net/browse/PC-10780

(PC-10780) Afficher en priorité la playlist taggée master
